<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Item</h1>
                </div>
                <div class="paragraph">
                    <p>Input Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <img src="pictures/close.svg"/>
                    </div>
                </div>
            </div>
            <form class="">
                <div class="popup-bot">
                    <!-- <div class="form-group">
                        <label for="additional-quantity">Add Quantity</label>
                        <input type="number" id="additional-quantity" name="quantity" placeholder="Enter quantity to add" />
                    </div> -->
                    <div class="form-group">
                        <label for="location">Location</label>
                        <input type="text" id="location" name="location" placeholder="Enter location" />
                    </div>
                    <div class="form-group">
                        <label for="serials">Serial Number</label>
                        <input type="text" id="serials" name="serials" placeholder="Enter serial number" />
                    </div>
                </div>
                <div class="popup-footer">
                    <button>Save Item</button>
                </div>
            </form>
        </div>
    </div>
</div>